### ISSUE TITLE
get started button still goes to incorrect link

### ISSUE THREAD

**Issue by rmflight** [tinystats/teacups-giraffes-and-statistics#10]
When I hit the Get Started button on the front page, it still goes to 

`https://tinystats.github.io/teacups-giraffes-and-statistics/introToR.html`,

not 

`https://tinystats.github.io/teacups-giraffes-and-statistics/01_introToR.html`

Which is odd, because everything I see in the code of the site points to the correct location.

**Comment by mcguinlu** [comment]
Super cool project! 

Just on a similar note to the above, the link to the "Intro to R" webpage in the GitHub README also points to the wrong site: `https://tinystats.github.io/teacups-giraffes-and-statistics/introToR.html`

Re: the "Getting started" link, I think the issue is that the link is correct in the [assests/Landing_page.html](https://github.com/tinystats/teacups-giraffes-and-statistics/blob/master/assets/Landing_page.html) document, but not in the [docs/assets/Landing_page.html](https://github.com/tinystats/teacups-giraffes-and-statistics/blob/master/docs/assets/Landing_page.html) document. I'm guessing is the folder the site is being hosted from the docs/ folder, causing the issue. Out of interest, I changed the link in a forked [docs/assets/Landing_page.html](https://github.com/mcguinlu/teacups-giraffes-and-statistics/blob/master/docs/assets/Landing_page.html) document and hosted the page to check it fixed the issue - https://mcguinlu.github.io/teacups-giraffes-and-statistics/index.html - which it did.

It might be that the change was made to the source document (assests/Landing_page.html) but the book wasn't built again?

[Still new to GH, so apologies if I commit any faux pas!]

**Comment by dcossyleon** [comment]
Thanks, @rmflight and @mcguinlu, for catching this. 

@mcguinlu you were right-- a re-knitting of the source `.Rmd` fixed the problem.
